version: "3"

services:

  nodeserver:
    image: "keymetrics/pm2:8-stretch"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./../:/home/node/app
    ports:
      - "${HTTP_PORT}:${NODE_HTTP_PORT}"
      - "${SERVER_DEBUG_PORT}:9230"
      - "${TESTS_DEBUG_PORT}:9231"
    command: "pm2-runtime pm2.config.js --only bruce-${PM2_CONFIG_ENVIRONMENT}"
    networks:
      - webnet


networks:
    webnet:   