// createProjectDirectory();
// createCodeDirectory();
// linkCodeToProject();
// setupDockerEnvironment();
// startDocker();
// installNpmPackages();
// setupWebpack();
// createCodeFramework();
// gitCommit();